### PR TITLE
Initial scaffolding

### PR DESCRIPTION
**Pull request by cmgrote**
Signed-off-by: Christopher Grote <chris@thegrotes.net>

### CODE REVIEW

**Comment by cmgrote** [comment]
@jmertic can you add the DCO check to this repo? 🙏 

@schannamallu can you setup the Jenkins build for this repo, same config as for odpi/egeria-connector-ibm-igc (tracked via https://github.com/odpi/ci-management/issues/93)? 🙏 

And not sure who controls the mandatory review bit (remove to be inline with other projects)?

**Comment by jmertic** [comment]
@cmgrote The DCO check is there - you can look through the checks above and see :-)

**Comment by cmgrote** [comment]
Right you are, sorry!

**Comment by cmgrote** [comment]
recheck

**Comment by cmgrote** [comment]
@jmertic can you remove the mandatory review for PRs on this repo, to be inline with the other repos? 🙏

**Pull request merged**
